### ISSUE TITLE
1.14.3 Redstone cannot be mined. 

### ISSUE THREAD

**Issue by Ake247** [Aang23/UndergroundBiomesConstructs#115]
Game Crashes when mining redstone. 

 Description: Unexpected error

java.lang.IllegalArgumentException: Cannot get property BooleanProperty{name=lit, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in Block{undergroundbiomes:igneous_ore_minecraft_redstone_ore_black_granite}
	at net.minecraft.state.StateHolder.func_177229_b(SourceFile:95) ~[?:?] {}
	at net.minecraft.block.RedstoneOreBlock.func_196500_d(RedstoneOreBlock.java:49) ~[?:?] {}
	at net.minecraft.block.RedstoneOreBlock.func_196270_a(RedstoneOreBlock.java:33) ~[?:?] {}
	at com.aang23.undergroundbiomes.blocks.ore.UBOre.func_196270_a(UBOre.java:112) ~[?:1.0-32] {}
	at net.minecraft.block.BlockState.func_196942_a(BlockState.java:278) ~[?:?] {}
	at net.minecraft.client.multiplayer.PlayerController.func_180511_b(PlayerController.java:170) ~[?:?] {pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_147116_af(Minecraft.java:1188) ~[?:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:1480) ~[?:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1316) ~[?:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:864) [?:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:384) [?:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:154) [?:?] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.14.3-27.0.13.jar:27.0] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$331/821342630.call(Unknown Source) [forge-1.14.3-27.0.13.jar:27.0] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-2.1.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:50) [modlauncher-2.1.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:68) [modlauncher-2.1.4.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:77) [modlauncher-2.1.4.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:62) [modlauncher-2.1.4.jar:?] {}

**Comment by Ake247** [comment]
Still crashes mining Redstone with updated UndergroundBiomes-1.14.3-1.0-33.jar
Download where Changelog states:- no more crash when mining Redstone Ore

**Comment by Aang23** [comment]
I know... It'll be fixed don't worry.

**Comment by Ake247** [comment]
Thanks for the fast reply. I don't know if this will help but I noticed that an import might be missing from the UBOre.class. Redstone has its own block file with its functions, so I didn't know if you needed to import the RestoneOreBlock.class within the UBOre.class.  I would have tested it out but I'm still new to coding. Can't see to understand how to decompile and correct then recompile. tried many times but might not be using the right software.

**Comment by Aang23** [comment]
This wouldn't work. All blocks uses the same "base", thus there's no point in importing something specific.
To compile just run ./gradlew build / gradlew build (windows).

**Comment by Ake247** [comment]
Thanks for the advice and great job on the mod. Big fan!

**Comment by Aang23** [comment]
For some reason I couldn't reproduce your crash.

**Comment by Ake247** [comment]
Ok I'll just do a test on an install with that mod only. What version minecraft, and forge did you use?

**Comment by Ake247** [comment]
I used Forge 27.0.25 with the download off CurseForge, 1.14.3-1.0.33, and on Minecraft 1.14.3 and I still get the same error. I'll just have to avoid redstone till the next update. Thanks for all the help

**Comment by Ake247** [comment]
New update fixed issue. I don't really know what the deal was but its fixed. great job and love the mod keep it up. Underground partnered along with biomes o plenty makes a great world with tons of building options.
