### ISSUE TITLE
Errors after installing the mod

### ISSUE THREAD

**Issue by kellixon** [Aang23/UndergroundBiomesConstructs#31]
MC 1.12.2. UndergroundBiomesConstructs 1.3.1. Part of the log
`
....................
[14:03:03] [Server thread/ERROR] [net.minecraft.advancements.AdvancementManager]: Parsing error loading built-in advancement minecraft:recipes/redstone/stone_button
com.google.gson.JsonSyntaxException: Unknown recipe 'minecraft:stone_button'
	at net.minecraft.advancements.AdvancementRewards$Deserializer.deserialize(AdvancementRewards.java:171) ~[l$a.class:?]
	at net.minecraft.advancements.AdvancementRewards$Deserializer.deserialize(AdvancementRewards.java:147) ~[l$a.class:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[TreeTypeAdapter.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[Gson.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:952) ~[Gson.class:?]
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[TreeTypeAdapter$GsonContextImpl.class:?]
	at net.minecraft.util.JsonUtils.deserializeClass(SourceFile:439) ~[rc.class:?]
	at net.minecraft.util.JsonUtils.deserializeClass(SourceFile:455) ~[rc.class:?]
	at net.minecraft.advancements.Advancement$Builder.deserialize(SourceFile:203) ~[i$a.class:?]
	at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:50) ~[ns$1.class:?]
	at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:46) ~[ns$1.class:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[TreeTypeAdapter.class:?]
	at net.minecraft.util.JsonUtils.gsonDeserialize(SourceFile:492) ~[rc.class:?]
	at net.minecraft.util.JsonUtils.fromJson(SourceFile:532) ~[rc.class:?]
	at net.minecraft.advancements.AdvancementManager.loadBuiltInAdvancements(AdvancementManager.java:184) [ns.class:?]
	at net.minecraft.advancements.AdvancementManager.reload(AdvancementManager.java:68) [ns.class:?]
	at net.minecraft.advancements.AdvancementManager.<init>(AdvancementManager.java:60) [ns.class:?]
	at net.minecraft.world.WorldServer.init(WorldServer.java:156) [oo.class:?]
	at net.minecraft.server.integrated.IntegratedServer.loadAllWorlds(IntegratedServer.java:99) [chd.class:?]
	at net.minecraft.server.integrated.IntegratedServer.init(IntegratedServer.java:213) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_192]
[14:03:03] [Server thread/ERROR] [net.minecraft.advancements.AdvancementManager]: Parsing error loading built-in advancement minecraft:recipes/building_blocks/mossy_cobblestone
com.google.gson.JsonSyntaxException: Unknown recipe 'minecraft:mossy_cobblestone'
	at net.minecraft.advancements.AdvancementRewards$Deserializer.deserialize(AdvancementRewards.java:171) ~[l$a.class:?]
	at net.minecraft.advancements.AdvancementRewards$Deserializer.deserialize(AdvancementRewards.java:147) ~[l$a.class:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[TreeTypeAdapter.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[Gson.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:952) ~[Gson.class:?]
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[TreeTypeAdapter$GsonContextImpl.class:?]
	at net.minecraft.util.JsonUtils.deserializeClass(SourceFile:439) ~[rc.class:?]
	at net.minecraft.util.JsonUtils.deserializeClass(SourceFile:455) ~[rc.class:?]
	at net.minecraft.advancements.Advancement$Builder.deserialize(SourceFile:203) ~[i$a.class:?]
	at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:50) ~[ns$1.class:?]
	at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:46) ~[ns$1.class:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[TreeTypeAdapter.class:?]
	at net.minecraft.util.JsonUtils.gsonDeserialize(SourceFile:492) ~[rc.class:?]
	at net.minecraft.util.JsonUtils.fromJson(SourceFile:532) ~[rc.class:?]
	at net.minecraft.advancements.AdvancementManager.loadBuiltInAdvancements(AdvancementManager.java:184) [ns.class:?]
	at net.minecraft.advancements.AdvancementManager.reload(AdvancementManager.java:68) [ns.class:?]
	at net.minecraft.advancements.AdvancementManager.<init>(AdvancementManager.java:60) [ns.class:?]
	at net.minecraft.world.WorldServer.init(WorldServer.java:156) [oo.class:?]
	at net.minecraft.server.integrated.IntegratedServer.loadAllWorlds(IntegratedServer.java:99) [chd.class:?]
	at net.minecraft.server.integrated.IntegratedServer.init(IntegratedServer.java:213) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_192]
[14:03:08] [Server thread/INFO] [net.minecraft.advancements.AdvancementList]: Loaded 986 advancements
[14:03:08] [Server thread/DEBUG] [mixin]: Mixing MixinBlockStateContainer from mixins.vanillafix.bugs.json into net.minecraft.world.chunk.BlockStateContainer
[14:03:08] [Server thread/TRACE] [mixin]: Added class metadata for net/minecraft/util/BitArray to metadata cache
[14:03:08] [Server thread/INFO] [THAUMCRAFT]: Creating aura cache for world 0
[14:03:08] [Server thread/DEBUG] [FML]: Attempting to inject @Config classes into ftbutilities for type INSTANCE
[14:03:08] [Server thread/DEBUG] [FML]: Attempting to inject @Config classes into ftblib for type INSTANCE
[14:03:09] [Server thread/ERROR] [net.minecraft.advancements.AdvancementManager]: Parsing error loading built-in advancement minecraft:recipes/redstone/stone_button
com.google.gson.JsonSyntaxException: Unknown recipe 'minecraft:stone_button'
	at net.minecraft.advancements.AdvancementRewards$Deserializer.deserialize(AdvancementRewards.java:171) ~[l$a.class:?]
	at net.minecraft.advancements.AdvancementRewards$Deserializer.deserialize(AdvancementRewards.java:147) ~[l$a.class:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[TreeTypeAdapter.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[Gson.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:952) ~[Gson.class:?]
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[TreeTypeAdapter$GsonContextImpl.class:?]
	at net.minecraft.util.JsonUtils.deserializeClass(SourceFile:439) ~[rc.class:?]
	at net.minecraft.util.JsonUtils.deserializeClass(SourceFile:455) ~[rc.class:?]
	at net.minecraft.advancements.Advancement$Builder.deserialize(SourceFile:203) ~[i$a.class:?]
	at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:50) ~[ns$1.class:?]
	at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:46) ~[ns$1.class:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[TreeTypeAdapter.class:?]
	at net.minecraft.util.JsonUtils.gsonDeserialize(SourceFile:492) ~[rc.class:?]
	at net.minecraft.util.JsonUtils.fromJson(SourceFile:532) ~[rc.class:?]
	at net.minecraft.advancements.AdvancementManager.loadBuiltInAdvancements(AdvancementManager.java:184) [ns.class:?]
	at net.minecraft.advancements.AdvancementManager.reload(AdvancementManager.java:68) [ns.class:?]
	at net.minecraft.server.MinecraftServer.reload(MinecraftServer.java:1429) [MinecraftServer.class:?]
	at com.feed_the_beast.ftblib.lib.data.FTBLibAPI.reloadServer(FTBLibAPI.java:105) [FTBLibAPI.class:?]
	at com.feed_the_beast.ftblib.lib.data.Universe.load(Universe.java:521) [Universe.class:?]
	at com.feed_the_beast.ftblib.lib.data.Universe.onWorldLoaded(Universe.java:130) [Universe.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_217_Universe_onWorldLoaded_Load.invoke(.dynamic) [?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_192]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_192]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_192]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_192]
	at net.optifine.reflect.Reflector.call(Reflector.java:967) [Reflector.class:?]
	at net.optifine.reflect.Reflector.postForgeBusEvent(Reflector.java:1242) [Reflector.class:?]
	at net.optifine.reflect.Reflector.postForgeBusEvent(Reflector.java:1228) [Reflector.class:?]
	at net.minecraft.server.integrated.IntegratedServer.loadAllWorlds(IntegratedServer.java:117) [chd.class:?]
	at net.minecraft.server.integrated.IntegratedServer.init(IntegratedServer.java:213) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_192]
[14:03:09] [Server thread/ERROR] [net.minecraft.advancements.AdvancementManager]: Parsing error loading built-in advancement minecraft:recipes/building_blocks/mossy_cobblestone
com.google.gson.JsonSyntaxException: Unknown recipe 'minecraft:mossy_cobblestone'
	at net.minecraft.advancements.AdvancementRewards$Deserializer.deserialize(AdvancementRewards.java:171) ~[l$a.class:?]
	at net.minecraft.advancements.AdvancementRewards$Deserializer.deserialize(AdvancementRewards.java:147) ~[l$a.class:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[TreeTypeAdapter.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[Gson.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:952) ~[Gson.class:?]
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[TreeTypeAdapter$GsonContextImpl.class:?]
	at net.minecraft.util.JsonUtils.deserializeClass(SourceFile:439) ~[rc.class:?]
	at net.minecraft.util.JsonUtils.deserializeClass(SourceFile:455) ~[rc.class:?]
	at net.minecraft.advancements.Advancement$Builder.deserialize(SourceFile:203) ~[i$a.class:?]
	at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:50) ~[ns$1.class:?]
	at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:46) ~[ns$1.class:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[TreeTypeAdapter.class:?]
	at net.minecraft.util.JsonUtils.gsonDeserialize(SourceFile:492) ~[rc.class:?]
	at net.minecraft.util.JsonUtils.fromJson(SourceFile:532) ~[rc.class:?]
	at net.minecraft.advancements.AdvancementManager.loadBuiltInAdvancements(AdvancementManager.java:184) [ns.class:?]
	at net.minecraft.advancements.AdvancementManager.reload(AdvancementManager.java:68) [ns.class:?]
	at net.minecraft.server.MinecraftServer.reload(MinecraftServer.java:1429) [MinecraftServer.class:?]
	at com.feed_the_beast.ftblib.lib.data.FTBLibAPI.reloadServer(FTBLibAPI.java:105) [FTBLibAPI.class:?]
	at com.feed_the_beast.ftblib.lib.data.Universe.load(Universe.java:521) [Universe.class:?]
	at com.feed_the_beast.ftblib.lib.data.Universe.onWorldLoaded(Universe.java:130) [Universe.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_217_Universe_onWorldLoaded_Load.invoke(.dynamic) [?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_192]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_192]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_192]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_192]
	at net.optifine.reflect.Reflector.call(Reflector.java:967) [Reflector.class:?]
	at net.optifine.reflect.Reflector.postForgeBusEvent(Reflector.java:1242) [Reflector.class:?]
	at net.optifine.reflect.Reflector.postForgeBusEvent(Reflector.java:1228) [Reflector.class:?]
	at net.minecraft.server.integrated.IntegratedServer.loadAllWorlds(IntegratedServer.java:117) [chd.class:?]
	at net.minecraft.server.integrated.IntegratedServer.init(IntegratedServer.java:213) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_192]
.........................................
`

**Comment by Aang23** [comment]
I'll close this one since https://github.com/Aang23/UndergroundBiomesConstructs/issues/51 is about the same issue.
