### ISSUE TITLE
Crashes on World Generation with BoP

### ISSUE THREAD

**Issue by Quidrex** [Aang23/UndergroundBiomesConstructs#36]
Forge: 1.12.2-14.23.5.2768
UndergroundBiomesConstructs: 1.12-1.2.1
Biomes O'Plenty: 1.12.2-7.0.1.2419

When generating chunks with Biomes O'Plenty enabled the server crashes randomly with exceptions like:
```[21:15:50] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.terraingen.BiomeEvent$GetVillageBlockID@376e02f3:
java.lang.RuntimeException: null
	at exterminatorjeff.undergroundbiomes.world.WorldGenManager.onVillageSelectBlock(WorldGenManager.java:155) ~[WorldGenManager.class:?]
	at exterminatorjeff.undergroundbiomes.core.DimensionManager.onVillageSelectBlock(DimensionManager.java:122) ~[DimensionManager.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_621_DimensionManager_onVillageSelectBlock_GetVillageBlockID.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraft.world.gen.structure.StructureVillagePieces$Village.func_175847_a(StructureVillagePieces.java:1811) [bcb$n.class:?]
	at net.minecraft.world.gen.structure.StructureVillagePieces$Village.func_175808_b(StructureVillagePieces.java:1929) [bcb$n.class:?]
	at forestry.apiculture.worldgen.VillageApiaristHouse.func_74875_a(VillageApiaristHouse.java:224) [VillageApiaristHouse.class:?]
	at net.minecraft.world.gen.structure.StructureStart.func_75068_a(StructureStart.java:47) [bby.class:?]
	at net.minecraft.world.gen.structure.MapGenStructure.func_175794_a(MapGenStructure.java:94) [bbu.class:?]
	at biomesoplenty.common.world.ChunkGeneratorOverworldBOP.func_185931_b(ChunkGeneratorOverworldBOP.java:509) [ChunkGeneratorOverworldBOP.class:?]
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1019) [axw.class:?]
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:999) [axw.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157) [on.class:?]
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126) [ot.class:?]
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147) [ou.class:?]
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227) [oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
[21:15:50] [Server thread/ERROR] [FML]: Index: 2 Listeners:
[21:15:50] [Server thread/ERROR] [FML]: 0: NORMAL
[21:15:50] [Server thread/ERROR] [FML]: 1: ASM: biomesoplenty.common.handler.VillageMaterialEventHandler@4c5fa67e getVillageBlockID(Lnet/minecraftforge/event/terraingen/BiomeEvent$GetVillageBlockID;)V
[21:15:50] [Server thread/ERROR] [FML]: 2: ASM: exterminatorjeff.undergroundbiomes.core.DimensionManager@78b79415 onVillageSelectBlock(Lnet/minecraftforge/event/terraingen/BiomeEvent$GetVillageBlockID;)V
[21:15:50] [Server thread/WARN] [enderio]: @Devs: See github for dev env setup; set INDEV if needed.
[21:15:50] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Exception ticking world
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:762) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.RuntimeException
	at exterminatorjeff.undergroundbiomes.world.WorldGenManager.onVillageSelectBlock(WorldGenManager.java:155) ~[WorldGenManager.class:?]
	at exterminatorjeff.undergroundbiomes.core.DimensionManager.onVillageSelectBlock(DimensionManager.java:122) ~[DimensionManager.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_621_DimensionManager_onVillageSelectBlock_GetVillageBlockID.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
	at net.minecraft.world.gen.structure.StructureVillagePieces$Village.func_175847_a(StructureVillagePieces.java:1811) ~[bcb$n.class:?]
	at net.minecraft.world.gen.structure.StructureVillagePieces$Village.func_175808_b(StructureVillagePieces.java:1929) ~[bcb$n.class:?]
	at forestry.apiculture.worldgen.VillageApiaristHouse.func_74875_a(VillageApiaristHouse.java:224) ~[VillageApiaristHouse.class:?]
	at net.minecraft.world.gen.structure.StructureStart.func_75068_a(StructureStart.java:47) ~[bby.class:?]
	at net.minecraft.world.gen.structure.MapGenStructure.func_175794_a(MapGenStructure.java:94) ~[bbu.class:?]
	at biomesoplenty.common.world.ChunkGeneratorOverworldBOP.func_185931_b(ChunkGeneratorOverworldBOP.java:509) ~[ChunkGeneratorOverworldBOP.class:?]
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1019) ~[axw.class:?]
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:999) ~[axw.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157) ~[on.class:?]
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126) ~[ot.class:?]
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147) ~[ou.class:?]
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227) ~[oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756) ~[MinecraftServer.class:?]
	... 4 more
```

This is caused by Biomes O'Plenty setting the event to DENY and UndergroundBiomes throwing a RuntimeException on DENY. How did these mods ever work together, this does not seem to be new behaviour in either one?

**Comment by Quidrex** [comment]
I quickfixed/tested by including the following at the beginning of onVillageSelectBlock:
```
if (event.getResult().equals(Result.DENY)) {
  return;
}
```

Even then we got a crash after a few minutes of exploration:

```[02:40:04] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.terraingen.BiomeEvent$GetVillageBlockID@24f1b539:
java.lang.RuntimeException: Block{minecraft:sand}
	at exterminatorjeff.undergroundbiomes.world.WorldGenManager.onVillageSelectBlock(WorldGenManager.java:259) ~[WorldGenManager.class:?]
	at exterminatorjeff.undergroundbiomes.core.DimensionManager.onVillageSelectBlock(DimensionManager.java:120) ~[DimensionManager.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_620_DimensionManager_onVillageSelectBlock_GetVillageBlockID.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraft.world.gen.structure.StructureVillagePieces$Village.func_175847_a(StructureVillagePieces.java:1811) [bcb$n.class:?]
	at net.minecraft.world.gen.structure.StructureVillagePieces$Village.func_175808_b(StructureVillagePieces.java:1929) [bcb$n.class:?]
	at forestry.apiculture.worldgen.VillageApiaristHouse.buildGarden(VillageApiaristHouse.java:262) [VillageApiaristHouse.class:?]
	at forestry.apiculture.worldgen.VillageApiaristHouse.func_74875_a(VillageApiaristHouse.java:112) [VillageApiaristHouse.class:?]
	at net.minecraft.world.gen.structure.StructureStart.func_75068_a(StructureStart.java:47) [bby.class:?]
	at net.minecraft.world.gen.structure.MapGenStructure.func_175794_a(MapGenStructure.java:94) [bbu.class:?]
	at biomesoplenty.common.world.ChunkGeneratorOverworldBOP.func_185931_b(ChunkGeneratorOverworldBOP.java:509) [ChunkGeneratorOverworldBOP.class:?]
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1019) [axw.class:?]
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:990) [axw.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157) [on.class:?]
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126) [ot.class:?]
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147) [ou.class:?]
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227) [oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
```

So now I'm temporarily "fixing" it by commenting out the whole event handler.

**Comment by Aang23** [comment]
Could you try with 1.3.1 ?
I ran a server with BOP and UBC for a while recently, and I did not have that kind of an issue.

**Comment by Aang23** [comment]
@Quidrex Could you post you entire mod list ? Or the full crash report / logs ? I think that it's neither UBC or BOP's fault.

**Comment by Quidrex** [comment]
The Logs are too large for Pastebin, so download from my nextCloud:
First Log: https://stuart.quidrex.de/owncloud/index.php/s/s8xty2XeQWXogr7
Second Log (with my workaround): https://stuart.quidrex.de/owncloud/index.php/s/8a9HbrPcPCMFDtT

From the logs I can't seem to find another mod interfering and the first crash is definitely from BoP DENYing the event and UBC throwing an empty RuntimeException as a result. The second one seems to be caused by UBC not expecting sand to be in villages, this could be from another mod. Weird. Any list of event listeners you need?

Full modlist (now with self-compiled UBC):
``` mods/AlbedoTorches-1.0.4.jar                         mods/Farseek-1.12-2.3.1.jar                          mods/Plants-1.12.2-2.10.3.jar                          mods/autoplant-1.12-1.0.0.jar
 mods/AppleCore-mc1.12.2-3.1.4.jar                    mods/Forgelin-1.8.2.jar                              mods/RedstoneFlux-1.12-2.1.0.6-universal.jar           mods/backpack-3.0.2-1.12.2.jar
 mods/AppleSkin-mc1.12-1.0.9.jar                      mods/GalacticraftCore-1.12.2-4.0.1.181.jar           mods/Ruins-Mod-1.12.2.jar                              mods/forestry_1.12.2-5.8.2.374.jar
 mods/BetterFoliage-MC1.12-2.2.0.jar                  mods/Galacticraft-Planets-1.12.2-4.0.1.181.jar       mods/SimpleDimensions-MC1.12-1.4.jar                   mods/gravestone-1.10.2.jar
 mods/BetterFps-1.4.8.jar                             mods/Hats-1.12.2-7.0.2.jar                           mods/StorageDrawersExtras-1.12-3.1.1.jar               mods/hopperducts-mc1.12-1.5.jar
 mods/BiomesOPlenty-1.12.2-7.0.1.2419-universal.jar   mods/HungerOverhaul-1.12.2-1.3.3.jenkins148.jar      mods/StorageDrawers-1.12.2-5.3.8.jar                   mods/iChunUtil-1.12.2-7.1.4.jar
 mods/CTM-MC1.12.2-0.3.3.22.jar                       mods/Hwyla-1.8.26-B41_1.12.2.jar                     mods/Streams-1.12-0.4.4.jar                            mods/jei_1.12.2-4.14.3.237.jar
 mods/Chameleon-1.12-4.1.3.jar                        mods/InventoryTweaks-1.63.jar                        mods/TConstruct-1.12.2-2.11.0.106.jar                  mods/journeymap-1.12.2-5.5.3.jar
 mods/Chisel-MC1.12.2-0.2.1.35.jar                    mods/Mantle-1.12-1.3.3.39.jar                        mods/Terra-Mod-1.12.2.jar                              mods/mysticallib-1.12.2-1.0.0.jar
 mods/CoFHCore-1.12.2-4.6.1.22-universal.jar          mods/MicdoodleCore-1.12.2-4.0.1.181.jar              mods/ThermalExpansion-1.12.2-5.5.2.39-universal.jar    mods/rangedpumps-0.5.jar
 mods/CoFHWorld-1.12.2-1.3.0.6-universal.jar         'mods/NoMoreRecipeConflict-0.12(1.12.2).jar'          mods/ThermalFoundation-1.12.2-2.6.1.22-universal.jar   mods/redstonepaste-mc1.12-1.7.5.jar
 mods/CodeChickenLib-1.12.2-3.2.2.353-universal.jar   mods/NotEnoughItems-1.12.2-2.4.2.240-universal.jar   mods/TinkerToolLeveling-1.12.2-1.1.0.jar               mods/simpleportals-1.12.2-1.5.1.0.jar
 mods/Dynmap-3.0-beta-3-forge-1.12.2.jar              mods/OptiFine_1.12.2_HD_U_E3.jar                     mods/ToolsAndArmorBOP-1.12.2-1.0.0.jar                 mods/starterkit-1.12.2-1.0.18.1.jar
 mods/EnderCore-1.12.2-0.5.43.jar                     mods/OreBabelfish-1.12.2-1.0.jar                     mods/UndergroundBiomesConstructs-1.12-1.3.2.jar        mods/valkyrielib-1.12.2-2.0.18.3.jar
 mods/EnderIO-1.12.2-5.0.38.jar                      "mods/Pam's+HarvestCraft+1.12.2za.jar"                mods/aether_legacy-1.12.2-v3.2.jar                     mods/weirdinggadget-1.12.2-2.0.5-universal.jar
 mods/EnderStorage-1.12.2-2.4.5.135-universal.jar     mods/Placebo-1.12.2-1.5.0.jar                        mods/albedo-0.1.3.jar
```
The self-compiled is based on the latest commit, so includes the new blocks (any doc on that, does that affect only new chunks?). By the way, is it intended that with the new buttons the stone_button recipe gets completey disabled? Galacticraft recipes need buttons as input.

Thanks!

**Comment by Aang23** [comment]
@Quidrex, when reporting an issue that you think is related to known mods, please always update all of them to the latest version before reporting, chances that your issue has already been fixed are quite high.
I tested with BOP + UBC (both compiled from source) without any issues, running on a test server for 10 hours of constant world gen using Chunk Pregenerator. I did not test with your BOP version, as you should not be using it.

Does it happen without UBC ? Without BOP ?

However that onVillageSelectBlock() event handler is broken since quite a while now... So I may simply be removing it completely.

**Comment by Quidrex** [comment]
I'm sorry to have jumped to conclusions, I will further test this and try to find out which mod causes this. I saw the exception, looked at the code and did not think about the possibility that the crash on tick is not caused by the preceding exception from onVillageSelect().

Thanks!

**Comment by Aang23** [comment]
I'll close this unless something else shows up.
