### ISSUE TITLE
1.12.2 Achievements Break

### ISSUE THREAD

**Issue by O13SC3N3** [Aang23/UndergroundBiomesConstructs#51]
Greetings,

 

To give you a run down on what im actually doing here, is 1 by 1 I am going through 300 mods to find whats breaking the advancement system to cause mods like Reskillable and a few others like Nature's Aura etc issues and corrupting player data. (Seems to only corrupt player data once there is a certain amount of broken advancements) That is the theory anyway. So far everything is Vanilla with the exception of things like FoamFix etc, Right now only 2 Advancements (Recipes) are broken with UBC.

https://pastebin.com/raw/ycTjSC5W

Mossy Cobblestone and Stone Button, my guess is its missing the generic minecraft stone. Now when I enable generate vanilla variants as well. The issues are thrown still. This is only given once creating a world with ubc. I thought it would be Quark as well but without UBC its fine, and even disabled button renaming etc or stones, the error is still only present with UBC. 

Update:

# Replace mossy cobblestone with UB variants, great for dungeons !
B:ReplaceMossyCobble=false

# Provide buttons for Underground Biomes blocks
B:UndergroundBiomesButtons=false

Fixes both, but thats no fun :( thoughts?

**Comment by Aang23** [comment]
The issue is that recipes are removed, which causes the advancement system to trow that log, and breaks some advancements.
I knew that was an issue but didn't think that it would cause anything.

Changing those to false also affects world gen, recipes stays the same.

**Comment by Aang23** [comment]
(Same as https://github.com/Aang23/UndergroundBiomesConstructs/issues/44)

**Comment by Aang23** [comment]
(And https://github.com/Aang23/UndergroundBiomesConstructs/issues/31)

**Comment by Aang23** [comment]
Here's a test build. Could you tell me if it fixed your issue ?
https://drive.google.com/open?id=1xHny_iR6-ar68EUzIZe-nSHEH8ODimlH

**Comment by ianc1215** [comment]
I am seeing the same error on my server. I tried the BETA version of the UBC 1.3.2 that was provided. The server generated a crash-report when executed.

```
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Underground Biomes (undergroundbiomes)
Caused by: java.lang.NoSuchMethodError: net.minecraft.block.properties.PropertyEnum.create(Ljava/lang/String;Ljava/lang/Class;)Lnet/minecraft/block/properties/PropertyEnum;
    at exterminatorjeff.undergroundbiomes.api.enums.IgneousVariant.<clinit>(IgneousVariant.java:14)
    at exterminatorjeff.undergroundbiomes.config.UBConfig.<init>(UBConfig.java:107)
    at exterminatorjeff.undergroundbiomes.config.ConfigManager.<init>(ConfigManager.java:25)
    at exterminatorjeff.undergroundbiomes.core.CommonProxy.preInit(CommonProxy.java:59)
    at exterminatorjeff.undergroundbiomes.core.ServerProxy.preInit(ServerProxy.java:16)
    at exterminatorjeff.undergroundbiomes.core.UndergroundBiomes.preInit(UndergroundBiomes.java:52)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
    at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
    at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:99)
    at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333)
    at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:125)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
    at java.lang.Thread.run(Thread.java:748)
```

I also tried the 1.3.3 version from the Jenkins server and the error still occurs.

```
[18:47:01] [Server thread/ERROR] [minecraft/AdvancementManager]: Parsing error loading built-in advancement minecraft:recipes/redstone/stone_button
com.google.gson.JsonSyntaxException: Unknown recipe 'minecraft:stone_button'
        at net.minecraft.advancements.AdvancementRewards$Deserializer.deserialize(AdvancementRewards.java:171) ~[l$a.class:?]
        at net.minecraft.advancements.AdvancementRewards$Deserializer.deserialize(AdvancementRewards.java:147) ~[l$a.class:?]
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[TreeTypeAdapter.class:?]
        at com.google.gson.Gson.fromJson(Gson.java:887) ~[Gson.class:?]
        at com.google.gson.Gson.fromJson(Gson.java:952) ~[Gson.class:?]
        at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[TreeTypeAdapter$GsonContextImpl.class:?]
        at net.minecraft.util.JsonUtils.deserializeClass(SourceFile:439) ~[rc.class:?]
        at net.minecraft.util.JsonUtils.deserializeClass(SourceFile:455) ~[rc.class:?]
        at net.minecraft.advancements.Advancement$Builder.deserialize(SourceFile:203) ~[i$a.class:?]
        at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:50) ~[ns$1.class:?]
        at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:46) ~[ns$1.class:?]
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[TreeTypeAdapter.class:?]
        at net.minecraft.util.JsonUtils.gsonDeserialize(SourceFile:492) ~[rc.class:?]
        at net.minecraft.util.JsonUtils.fromJson(SourceFile:532) ~[rc.class:?]
        at net.minecraft.advancements.AdvancementManager.loadBuiltInAdvancements(AdvancementManager.java:184) [ns.class:?]
        at net.minecraft.advancements.AdvancementManager.reload(AdvancementManager.java:68) [ns.class:?]
        at net.minecraft.advancements.AdvancementManager.<init>(AdvancementManager.java:60) [ns.class:?]
        at net.minecraft.world.WorldServer.init(WorldServer.java:156) [oo.class:?]
        at net.minecraft.server.MinecraftServer.loadAllWorlds(MinecraftServer.java:298) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:270) [nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
[18:47:01] [Server thread/ERROR] [minecraft/AdvancementManager]: Parsing error loading built-in advancement minecraft:recipes/building_blocks/mossy_cobblestone
com.google.gson.JsonSyntaxException: Unknown recipe 'minecraft:mossy_cobblestone'
        at net.minecraft.advancements.AdvancementRewards$Deserializer.deserialize(AdvancementRewards.java:171) ~[l$a.class:?]
        at net.minecraft.advancements.AdvancementRewards$Deserializer.deserialize(AdvancementRewards.java:147) ~[l$a.class:?]
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[TreeTypeAdapter.class:?]
        at com.google.gson.Gson.fromJson(Gson.java:887) ~[Gson.class:?]
        at com.google.gson.Gson.fromJson(Gson.java:952) ~[Gson.class:?]
        at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[TreeTypeAdapter$GsonContextImpl.class:?]
        at net.minecraft.util.JsonUtils.deserializeClass(SourceFile:439) ~[rc.class:?]
        at net.minecraft.util.JsonUtils.deserializeClass(SourceFile:455) ~[rc.class:?]
        at net.minecraft.advancements.Advancement$Builder.deserialize(SourceFile:203) ~[i$a.class:?]
        at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:50) ~[ns$1.class:?]
        at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:46) ~[ns$1.class:?]
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[TreeTypeAdapter.class:?]
        at net.minecraft.util.JsonUtils.gsonDeserialize(SourceFile:492) ~[rc.class:?]
        at net.minecraft.util.JsonUtils.fromJson(SourceFile:532) ~[rc.class:?]
        at net.minecraft.advancements.AdvancementManager.loadBuiltInAdvancements(AdvancementManager.java:184) [ns.class:?]
        at net.minecraft.advancements.AdvancementManager.reload(AdvancementManager.java:68) [ns.class:?]
        at net.minecraft.advancements.AdvancementManager.<init>(AdvancementManager.java:60) [ns.class:?]
        at net.minecraft.world.WorldServer.init(WorldServer.java:156) [oo.class:?]
        at net.minecraft.server.MinecraftServer.loadAllWorlds(MinecraftServer.java:298) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:270) [nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
```

Just to be complete with my report this is JVM arguments and (important) mods I am running;

Java JVM
```
java -server -Xms1G -Xmx8G -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.port=9010 -Dcom.sun.management.jmemote.rmi.port=9011 -Dcom.sun.management.jmxremote.local.only=false -Djava.rmi.server.hostname=172.16.0.12 -Djava.net.preferIPv4Stack=true -jar forge-1.12.2-14.23.5.2768-universal.jar nogui noCoreSearch mixins.sgcraft.json
```

Mods
```
FoamFix
SpongeForge 7.1.5
VanillaFix 1.0.11
```

**Comment by O13SC3N3** [comment]
I've been away for awhile, the ability to create the moss stone and stone button is available but the original recipe/and error is still thrown.

**Comment by ianc1215** [comment]
Could the code that removes the stone_button and mossy_cobblestone recipes be removed for now so the error is suppressed? Actually, what is the purpose of removing the recipes in the first place? I don't 100% follow.

**Comment by O13SC3N3** [comment]
> Could the code that removes the stone_button and mossy_cobblestone recipes be removed for now so the error is suppressed? Actually, what is the purpose of removing the recipes in the first place? I don't 100% follow.

The stone buttons and cobble stone is replaced by variants of ubc stone added by the mod. UBC replaces all stone *unless changed to allow minecraft stone to generate in config" which if this option is enabled I think this could be fixed this way, but when I do, it does not.

**Comment by CREEATION** [comment]
So this is causing these errors?

```
[23:39:59] [main/ERROR]: Parsing error loading recipe undergroundbiomes:black_granite_stone_stairs
[23:39:59] [main/ERROR]: Parsing error loading recipe undergroundbiomes:red_granite_brick_wall
[23:39:59] [main/ERROR]: Parsing error loading recipe undergroundbiomes:eclogite_cobble_button
[23:39:59] [main/ERROR]: Parsing error loading recipe undergroundbiomes:komatiite_stone_wall
[23:39:59] [main/ERROR]: Parsing error loading recipe undergroundbiomes:migmatite_brick_wall
[23:39:59] [main/ERROR]: Parsing error loading recipe undergroundbiomes:blueschist_stone_wall
[23:40:00] [main/ERROR]: Parsing error loading recipe undergroundbiomes:komatiite_brick_wall
[23:40:00] [main/ERROR]: Parsing error loading recipe undergroundbiomes:quartzite_stone_stairs
[23:40:00] [main/ERROR]: Parsing error loading recipe undergroundbiomes:greenschist_cobble_button
[23:40:00] [main/ERROR]: Parsing error loading recipe undergroundbiomes:komatiite_stone_stairs
[23:40:00] [main/ERROR]: Parsing error loading recipe undergroundbiomes:soapstone_stone_stairs
[23:40:00] [main/ERROR]: Parsing error loading recipe undergroundbiomes:red_granite_stone_wall
[23:40:00] [main/ERROR]: Parsing error loading recipe undergroundbiomes:basalt_stone_stairs
[23:40:00] [main/ERROR]: Parsing error loading recipe undergroundbiomes:basalt_brick_wall
[23:40:00] [main/ERROR]: Parsing error loading recipe undergroundbiomes:andesite_cobble_button
[23:40:00] [main/ERROR]: Parsing error loading recipe undergroundbiomes:marble_stone_wall
[23:40:00] [main/ERROR]: Parsing error loading recipe undergroundbiomes:andesite_stone_wall
[23:40:00] [main/ERROR]: Parsing error loading recipe undergroundbiomes:gabbro_stone_stairs
[23:40:00] [main/ERROR]: Parsing error loading recipe undergroundbiomes:andesite_brick_wall
[23:40:00] [main/ERROR]: Parsing error loading recipe undergroundbiomes:quartzite_stone_wall
[23:40:00] [main/ERROR]: Parsing error loading recipe undergroundbiomes:dacite_stone_wall
[23:40:00] [main/ERROR]: Parsing error loading recipe undergroundbiomes:black_granite_stone_wall
[23:40:00] [main/ERROR]: Parsing error loading recipe undergroundbiomes:rhyolite_stone_wall
[23:40:00] [main/ERROR]: Parsing error loading recipe undergroundbiomes:gneiss_cobble_button
[23:40:00] [main/ERROR]: Parsing error loading recipe undergroundbiomes:soapstone_cobble_button
[23:40:00] [main/ERROR]: Parsing error loading recipe undergroundbiomes:red_granite_stone_stairs
[23:40:00] [main/ERROR]: Parsing error loading recipe undergroundbiomes:eclogite_brick_wall
[23:40:00] [main/ERROR]: Parsing error loading recipe undergroundbiomes:greenschist_stone_stairs
[23:40:00] [main/ERROR]: Parsing error loading recipe undergroundbiomes:blueschist_brick_wall
[23:40:00] [main/ERROR]: Parsing error loading recipe undergroundbiomes:basalt_cobble_button
[23:40:00] [main/ERROR]: Parsing error loading recipe undergroundbiomes:soapstone_brick_wall
[23:40:00] [main/ERROR]: Parsing error loading recipe undergroundbiomes:rhyolite_brick_wall
[23:40:00] [main/ERROR]: Parsing error loading recipe undergroundbiomes:dacite_stone_stairs
[23:40:00] [main/ERROR]: Parsing error loading recipe undergroundbiomes:gabbro_stone_wall
[23:40:00] [main/ERROR]: Parsing error loading recipe undergroundbiomes:gneiss_stone_stairs
[23:40:00] [main/ERROR]: Parsing error loading recipe undergroundbiomes:komatiite_cobble_button
[23:40:00] [main/ERROR]: Parsing error loading recipe undergroundbiomes:blueschist_stone_stairs
[23:40:00] [main/ERROR]: Parsing error loading recipe undergroundbiomes:gneiss_stone_wall
[23:40:00] [main/ERROR]: Parsing error loading recipe undergroundbiomes:migmatite_cobble_button
[23:40:00] [main/ERROR]: Parsing error loading recipe undergroundbiomes:gabbro_brick_wall
[23:40:00] [main/ERROR]: Parsing error loading recipe undergroundbiomes:migmatite_stone_wall
[23:40:00] [main/ERROR]: Parsing error loading recipe undergroundbiomes:soapstone_stone_wall
[23:40:00] [main/ERROR]: Parsing error loading recipe undergroundbiomes:dacite_brick_wall
[23:40:00] [main/ERROR]: Parsing error loading recipe undergroundbiomes:black_granite_cobble_button
[23:40:00] [main/ERROR]: Parsing error loading recipe undergroundbiomes:andesite_stone_stairs
[23:40:00] [main/ERROR]: Parsing error loading recipe undergroundbiomes:rhyolite_stone_stairs
[23:40:00] [main/ERROR]: Parsing error loading recipe undergroundbiomes:greenschist_brick_wall
[23:40:00] [main/ERROR]: Parsing error loading recipe undergroundbiomes:gabbro_cobble_button
[23:40:00] [main/ERROR]: Parsing error loading recipe undergroundbiomes:dacite_cobble_button
[23:40:00] [main/ERROR]: Parsing error loading recipe undergroundbiomes:basalt_stone_wall
[23:40:00] [main/ERROR]: Parsing error loading recipe undergroundbiomes:gneiss_brick_wall
[23:40:00] [main/ERROR]: Parsing error loading recipe undergroundbiomes:blueschist_cobble_button
[23:40:00] [main/ERROR]: Parsing error loading recipe undergroundbiomes:marble_cobble_button
[23:40:00] [main/ERROR]: Parsing error loading recipe undergroundbiomes:black_granite_brick_wall
[23:40:00] [main/ERROR]: Parsing error loading recipe undergroundbiomes:rhyolite_cobble_button
[23:40:00] [main/ERROR]: Parsing error loading recipe undergroundbiomes:quartzite_cobble_button
[23:40:00] [main/ERROR]: Parsing error loading recipe undergroundbiomes:eclogite_stone_stairs
[23:40:00] [main/ERROR]: Parsing error loading recipe undergroundbiomes:marble_brick_wall
[23:40:00] [main/ERROR]: Parsing error loading recipe undergroundbiomes:migmatite_stone_stairs
[23:40:00] [main/ERROR]: Parsing error loading recipe undergroundbiomes:red_granite_cobble_button
[23:40:00] [main/ERROR]: Parsing error loading recipe undergroundbiomes:greenschist_stone_wall
[23:40:00] [main/ERROR]: Parsing error loading recipe undergroundbiomes:marble_stone_stairs
[23:40:00] [main/ERROR]: Parsing error loading recipe undergroundbiomes:eclogite_stone_wall
[23:40:00] [main/ERROR]: Parsing error loading recipe undergroundbiomes:quartzite_brick_wall
```
